"""add bimestre score overrides to student enrollments

Revision ID: 28e6246549d2
Revises: 76f41b09b8c2
Create Date: 2026-07-02 15:46:26.234641
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "28e6246549d2"
down_revision: str | None = "76f41b09b8c2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "student_enrollments",
        sa.Column("aporte_1_override_score", sa.Numeric(precision=12, scale=4), nullable=True),
    )
    op.add_column(
        "student_enrollments",
        sa.Column("aporte_1_override_scale", sa.Numeric(precision=12, scale=4), nullable=True),
    )
    op.add_column(
        "student_enrollments",
        sa.Column("aporte_2_override_score", sa.Numeric(precision=12, scale=4), nullable=True),
    )
    op.add_column(
        "student_enrollments",
        sa.Column("aporte_2_override_scale", sa.Numeric(precision=12, scale=4), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("student_enrollments", "aporte_2_override_scale")
    op.drop_column("student_enrollments", "aporte_2_override_score")
    op.drop_column("student_enrollments", "aporte_1_override_scale")
    op.drop_column("student_enrollments", "aporte_1_override_score")
    # ### end Alembic commands ###
