"""initial schema

Revision ID: ee36e5670096
Revises: 
Create Date: 2026-06-30 21:25:00.995132
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'ee36e5670096'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institutions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('acronym', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_institutions'))
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('email_verified_at', sa.DateTime(), nullable=True),
    sa.Column('role', sa.Enum('STUDENT', 'ADMIN', 'SUPER_ADMIN', name='userrole', native_enum=False, length=40), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'DELETED', name='userstatus', native_enum=False, length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('academic_periods',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('institution_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('starts_on', sa.String(length=10), nullable=True),
    sa.Column('ends_on', sa.String(length=10), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], name=op.f('fk_academic_periods_institution_id_institutions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_academic_periods')),
    sa.UniqueConstraint('institution_id', 'code', name='uq_period_institution_code')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('before_snapshot', sa.JSON(), nullable=True),
    sa.Column('after_snapshot', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_audit_logs_actor_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_table('courses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('institution_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('default_credits', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('default_hours', sa.Integer(), nullable=False),
    sa.Column('course_type', sa.Enum('REGULAR', 'NON_CREDIT', 'PRACTICE', 'CAPSTONE', 'GRADUATION_REQUIREMENT', name='coursetype', native_enum=False, length=40), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], name=op.f('fk_courses_institution_id_institutions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_courses')),
    sa.UniqueConstraint('institution_id', 'code', name='uq_course_institution_code')
    )
    op.create_index(op.f('ix_courses_code'), 'courses', ['code'], unique=False)
    op.create_index(op.f('ix_courses_normalized_name'), 'courses', ['normalized_name'], unique=False)
    op.create_table('faculties',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('institution_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('acronym', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], name=op.f('fk_faculties_institution_id_institutions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_faculties'))
    )
    op.create_table('graduation_requirements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('institution_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('requirement_type', sa.Enum('ENGLISH', 'SPORTS', 'CLUBS', 'SOCIAL', 'ENTREPRENEURSHIP', 'ENVIRONMENT', 'PROJECTS', 'OTHER', name='graduationrequirementtype', native_enum=False, length=40), nullable=False),
    sa.Column('grants_credits', sa.Boolean(), nullable=False),
    sa.Column('credits', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], name=op.f('fk_graduation_requirements_institution_id_institutions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_graduation_requirements')),
    sa.UniqueConstraint('institution_id', 'code', name='uq_grad_req_institution_code')
    )
    op.create_table('professors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('institution_id', sa.Uuid(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], name=op.f('fk_professors_institution_id_institutions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_professors'))
    )
    op.create_table('careers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('faculty_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('degree_title', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculties.id'], name=op.f('fk_careers_faculty_id_faculties')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_careers'))
    )
    op.create_table('curricula',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('career_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('pensum_year', sa.Integer(), nullable=False),
    sa.Column('total_credits', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('total_hours', sa.Integer(), nullable=False),
    sa.Column('total_terms', sa.Integer(), nullable=False),
    sa.Column('total_courses_reported', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'ARCHIVED', name='curriculumstatus', native_enum=False, length=40), nullable=False),
    sa.Column('supersedes_curriculum_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['career_id'], ['careers.id'], name=op.f('fk_curricula_career_id_careers')),
    sa.ForeignKeyConstraint(['supersedes_curriculum_id'], ['curricula.id'], name=op.f('fk_curricula_supersedes_curriculum_id_curricula')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_curricula')),
    sa.UniqueConstraint('career_id', 'pensum_year', name='uq_curriculum_career_year')
    )
    op.create_table('course_offerings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('academic_period_id', sa.Uuid(), nullable=False),
    sa.Column('curriculum_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'ARCHIVED', name='courseofferingstatus', native_enum=False, length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['academic_period_id'], ['academic_periods.id'], name=op.f('fk_course_offerings_academic_period_id_academic_periods')),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_course_offerings_course_id_courses')),
    sa.ForeignKeyConstraint(['curriculum_id'], ['curricula.id'], name=op.f('fk_course_offerings_curriculum_id_curricula')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course_offerings'))
    )
    op.create_table('curriculum_courses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('curriculum_id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('reference_term', sa.Integer(), nullable=False),
    sa.Column('credits', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('hours', sa.Integer(), nullable=False),
    sa.Column('organization_unit', sa.Enum('BASIC', 'PROFESSIONAL', 'CAPSTONE', 'OTHER', name='organizationunit', native_enum=False, length=40), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_curriculum_courses_course_id_courses')),
    sa.ForeignKeyConstraint(['curriculum_id'], ['curricula.id'], name=op.f('fk_curriculum_courses_curriculum_id_curricula')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_curriculum_courses')),
    sa.UniqueConstraint('curriculum_id', 'course_id', name='uq_curriculum_course')
    )
    op.create_table('curriculum_graduation_requirements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('curriculum_id', sa.Uuid(), nullable=False),
    sa.Column('graduation_requirement_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['curriculum_id'], ['curricula.id'], name=op.f('fk_curriculum_graduation_requirements_curriculum_id_curricula')),
    sa.ForeignKeyConstraint(['graduation_requirement_id'], ['graduation_requirements.id'], name=op.f('fk_curriculum_graduation_requirements_graduation_requirement_id_graduation_requirements')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_curriculum_graduation_requirements')),
    sa.UniqueConstraint('curriculum_id', 'graduation_requirement_id', name='uq_curriculum_grad_req')
    )
    op.create_table('student_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('current_curriculum_id', sa.Uuid(), nullable=True),
    sa.Column('english_level', sa.Enum('NONE', 'BASIC_1', 'BASIC_2', 'INTERMEDIATE_1', 'ADVANCED_1', 'ADVANCED_2', 'SUFFICIENCY_B1', name='englishlevel', native_enum=False, length=40), nullable=False),
    sa.Column('english_sufficiency', sa.Boolean(), nullable=False),
    sa.Column('english_last_required_level_enrolled', sa.Boolean(), nullable=False),
    sa.Column('has_english_exception_authorization', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['current_curriculum_id'], ['curricula.id'], name=op.f('fk_student_profiles_current_curriculum_id_curricula')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_student_profiles_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_profiles')),
    sa.UniqueConstraint('user_id', name=op.f('uq_student_profiles_user_id'))
    )
    op.create_table('course_requirements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('curriculum_course_id', sa.Uuid(), nullable=False),
    sa.Column('required_curriculum_course_id', sa.Uuid(), nullable=False),
    sa.Column('requirement_type', sa.Enum('PREREQUISITE', 'COREQUISITE', name='requirementtype', native_enum=False, length=40), nullable=False),
    sa.Column('rule_operator', sa.Enum('ALL', 'ANY', name='ruleoperator', native_enum=False, length=40), nullable=False),
    sa.Column('is_strict', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['curriculum_course_id'], ['curriculum_courses.id'], name=op.f('fk_course_requirements_curriculum_course_id_curriculum_courses')),
    sa.ForeignKeyConstraint(['required_curriculum_course_id'], ['curriculum_courses.id'], name=op.f('fk_course_requirements_required_curriculum_course_id_curriculum_courses')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course_requirements'))
    )
    op.create_table('sections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('course_offering_id', sa.Uuid(), nullable=False),
    sa.Column('section_code', sa.String(length=50), nullable=False),
    sa.Column('modality', sa.Enum('PRESENTIAL', 'ONLINE', 'HYBRID', 'UNKNOWN', name='modality', native_enum=False, length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['course_offering_id'], ['course_offerings.id'], name=op.f('fk_sections_course_offering_id_course_offerings')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sections'))
    )
    op.create_table('simulations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_profile_id', sa.Uuid(), nullable=True),
    sa.Column('curriculum_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('mode', sa.Enum('ANONYMOUS', 'SAVED', name='simulationmode', native_enum=False, length=40), nullable=False),
    sa.Column('input_snapshot', sa.JSON(), nullable=False),
    sa.Column('result_snapshot', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['curriculum_id'], ['curricula.id'], name=op.f('fk_simulations_curriculum_id_curricula')),
    sa.ForeignKeyConstraint(['student_profile_id'], ['student_profiles.id'], name=op.f('fk_simulations_student_profile_id_student_profiles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_simulations'))
    )
    op.create_table('student_course_states',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_profile_id', sa.Uuid(), nullable=False),
    sa.Column('curriculum_course_id', sa.Uuid(), nullable=False),
    sa.Column('state', sa.Enum('NOT_TAKEN', 'IN_PROGRESS', 'PASSED', 'FAILED', 'ANNULLED', name='coursestate', native_enum=False, length=40), nullable=False),
    sa.Column('academic_period_id', sa.Uuid(), nullable=True),
    sa.Column('final_score_40', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('final_score_20', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('source', sa.Enum('MANUAL', 'GRADEBOOK', 'SIMULATION', name='coursestatesource', native_enum=False, length=40), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=True),
    sa.Column('withdrawal_type', sa.String(length=50), nullable=True),
    sa.Column('annulment_reason', sa.Text(), nullable=True),
    sa.Column('annulment_authorized', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['academic_period_id'], ['academic_periods.id'], name=op.f('fk_student_course_states_academic_period_id_academic_periods')),
    sa.ForeignKeyConstraint(['curriculum_course_id'], ['curriculum_courses.id'], name=op.f('fk_student_course_states_curriculum_course_id_curriculum_courses')),
    sa.ForeignKeyConstraint(['student_profile_id'], ['student_profiles.id'], name=op.f('fk_student_course_states_student_profile_id_student_profiles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_course_states'))
    )
    op.create_table('student_graduation_requirement_states',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_profile_id', sa.Uuid(), nullable=False),
    sa.Column('graduation_requirement_id', sa.Uuid(), nullable=False),
    sa.Column('state', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'NOT_APPLICABLE', name='graduationrequirementstate', native_enum=False, length=40), nullable=False),
    sa.Column('completed_at', sa.String(length=10), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['graduation_requirement_id'], ['graduation_requirements.id'], name=op.f('fk_student_graduation_requirement_states_graduation_requirement_id_graduation_requirements')),
    sa.ForeignKeyConstraint(['student_profile_id'], ['student_profiles.id'], name=op.f('fk_student_graduation_requirement_states_student_profile_id_student_profiles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_graduation_requirement_states'))
    )
    op.create_table('evaluation_schemes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('academic_period_id', sa.Uuid(), nullable=True),
    sa.Column('section_id', sa.Uuid(), nullable=True),
    sa.Column('professor_id', sa.Uuid(), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PERSONAL', 'COMMUNITY_PENDING', 'COMMUNITY_VERIFIED', 'ADMIN_VERIFIED', 'ARCHIVED', name='evaluationschemestatus', native_enum=False, length=40), nullable=False),
    sa.Column('visibility', sa.Enum('PRIVATE', 'COMMUNITY', 'PUBLIC', name='visibility', native_enum=False, length=40), nullable=False),
    sa.Column('source_type', sa.Enum('MANUAL_STUDENT', 'MANUAL_ADMIN', 'SYLLABUS_AI', 'SYLLABUS_MANUAL', name='schemesourcetype', native_enum=False, length=40), nullable=False),
    sa.Column('approval_count', sa.Integer(), nullable=False),
    sa.Column('revision_number', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('context_hash', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['academic_period_id'], ['academic_periods.id'], name=op.f('fk_evaluation_schemes_academic_period_id_academic_periods')),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_evaluation_schemes_course_id_courses')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_evaluation_schemes_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['professor_id'], ['professors.id'], name=op.f('fk_evaluation_schemes_professor_id_professors')),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], name=op.f('fk_evaluation_schemes_section_id_sections')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evaluation_schemes'))
    )
    op.create_index(op.f('ix_evaluation_schemes_context_hash'), 'evaluation_schemes', ['context_hash'], unique=False)
    op.create_table('section_professors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('section_id', sa.Uuid(), nullable=False),
    sa.Column('professor_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('PRIMARY', 'ASSISTANT', 'COMPONENT_AC', 'COMPONENT_AP', 'OTHER', name='sectionprofessorrole', native_enum=False, length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['professor_id'], ['professors.id'], name=op.f('fk_section_professors_professor_id_professors')),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], name=op.f('fk_section_professors_section_id_sections')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_section_professors'))
    )
    op.create_table('evaluation_components',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('evaluation_scheme_id', sa.Uuid(), nullable=False),
    sa.Column('contribution', sa.Enum('APORTE_1', 'APORTE_2', name='contribution', native_enum=False, length=40), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('evaluation_type', sa.Enum('FORMATIVE', 'SUMMATIVE', 'UNKNOWN', name='evaluationtype', native_enum=False, length=40), nullable=False),
    sa.Column('weight_percent', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('score_scale', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_scheme_id'], ['evaluation_schemes.id'], name=op.f('fk_evaluation_components_evaluation_scheme_id_evaluation_schemes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evaluation_components'))
    )
    op.create_table('evaluation_scheme_audits',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('evaluation_scheme_id', sa.Uuid(), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('before_snapshot', sa.Text(), nullable=True),
    sa.Column('after_snapshot', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_evaluation_scheme_audits_actor_user_id_users')),
    sa.ForeignKeyConstraint(['evaluation_scheme_id'], ['evaluation_schemes.id'], name=op.f('fk_evaluation_scheme_audits_evaluation_scheme_id_evaluation_schemes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evaluation_scheme_audits'))
    )
    op.create_table('evaluation_scheme_votes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('evaluation_scheme_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('vote', sa.Enum('APPROVE', 'REJECT', name='schemevote', native_enum=False, length=40), nullable=False),
    sa.Column('context_hash', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_scheme_id'], ['evaluation_schemes.id'], name=op.f('fk_evaluation_scheme_votes_evaluation_scheme_id_evaluation_schemes')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_evaluation_scheme_votes_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evaluation_scheme_votes')),
    sa.UniqueConstraint('evaluation_scheme_id', 'user_id', name='uq_scheme_vote_user')
    )
    op.create_table('student_enrollments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_profile_id', sa.Uuid(), nullable=False),
    sa.Column('curriculum_course_id', sa.Uuid(), nullable=False),
    sa.Column('academic_period_id', sa.Uuid(), nullable=True),
    sa.Column('section_id', sa.Uuid(), nullable=True),
    sa.Column('professor_id', sa.Uuid(), nullable=True),
    sa.Column('evaluation_scheme_id', sa.Uuid(), nullable=True),
    sa.Column('state', sa.Enum('ACTIVE', 'COMPLETED', 'FAILED', 'ANNULLED', name='enrollmentstate', native_enum=False, length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['academic_period_id'], ['academic_periods.id'], name=op.f('fk_student_enrollments_academic_period_id_academic_periods')),
    sa.ForeignKeyConstraint(['curriculum_course_id'], ['curriculum_courses.id'], name=op.f('fk_student_enrollments_curriculum_course_id_curriculum_courses')),
    sa.ForeignKeyConstraint(['evaluation_scheme_id'], ['evaluation_schemes.id'], name=op.f('fk_student_enrollments_evaluation_scheme_id_evaluation_schemes')),
    sa.ForeignKeyConstraint(['professor_id'], ['professors.id'], name=op.f('fk_student_enrollments_professor_id_professors')),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], name=op.f('fk_student_enrollments_section_id_sections')),
    sa.ForeignKeyConstraint(['student_profile_id'], ['student_profiles.id'], name=op.f('fk_student_enrollments_student_profile_id_student_profiles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_enrollments'))
    )
    op.create_table('grade_component_states',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_enrollment_id', sa.Uuid(), nullable=False),
    sa.Column('evaluation_component_id', sa.Uuid(), nullable=False),
    sa.Column('mode', sa.Enum('DIRECT_SCORE', 'EQUAL_AVERAGE', 'CUSTOM_WEIGHTS', name='gradecomponentmode', native_enum=False, length=40), nullable=False),
    sa.Column('direct_score', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('calculated_score', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('score_scale', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_component_id'], ['evaluation_components.id'], name=op.f('fk_grade_component_states_evaluation_component_id_evaluation_components')),
    sa.ForeignKeyConstraint(['student_enrollment_id'], ['student_enrollments.id'], name=op.f('fk_grade_component_states_student_enrollment_id_student_enrollments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_grade_component_states'))
    )
    op.create_table('grade_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('grade_component_state_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('score', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('score_scale', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('internal_weight_percent', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('due_date', sa.String(length=10), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['grade_component_state_id'], ['grade_component_states.id'], name=op.f('fk_grade_items_grade_component_state_id_grade_component_states')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_grade_items'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grade_items')
    op.drop_table('grade_component_states')
    op.drop_table('student_enrollments')
    op.drop_table('evaluation_scheme_votes')
    op.drop_table('evaluation_scheme_audits')
    op.drop_table('evaluation_components')
    op.drop_table('section_professors')
    op.drop_index(op.f('ix_evaluation_schemes_context_hash'), table_name='evaluation_schemes')
    op.drop_table('evaluation_schemes')
    op.drop_table('student_graduation_requirement_states')
    op.drop_table('student_course_states')
    op.drop_table('simulations')
    op.drop_table('sections')
    op.drop_table('course_requirements')
    op.drop_table('student_profiles')
    op.drop_table('curriculum_graduation_requirements')
    op.drop_table('curriculum_courses')
    op.drop_table('course_offerings')
    op.drop_table('curricula')
    op.drop_table('careers')
    op.drop_table('professors')
    op.drop_table('graduation_requirements')
    op.drop_table('faculties')
    op.drop_index(op.f('ix_courses_normalized_name'), table_name='courses')
    op.drop_index(op.f('ix_courses_code'), table_name='courses')
    op.drop_table('courses')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('academic_periods')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('institutions')
    # ### end Alembic commands ###
